//! "Clear-quad" pipeline used to translate D3D9 mid-pass `Clear` calls.
//!
//! D3D9's `IDirect3DDevice9::Clear` is viewport-clipped and can fire at
//! any point during rendering. Metal has no equivalent — clears can
//! only happen as `MTLRenderPassDescriptor.loadAction = Clear` at
//! encoder-begin, and that action clears the **entire** attachment,
//! ignoring viewport.
//!
//! Ending the current encoder and starting a new one with
//! `loadAction = Clear` handles the common "one Clear at pass
//! start" case, but is wrong for atlas-tile patterns such as a
//! shared shadow-cascade tile atlas, where each per-tile sub-rect
//! `Clear` would wipe the whole texture and delete every prior
//! tile's caster draws.
//!
//! Instead this path emits a fullscreen-triangle draw inside the
//! current encoder, scissored to the D3D9 viewport, whose VS writes
//! the caller-supplied clear value as constant depth (and the FS
//! writes `clear_color` to the bound color attachment when one
//! exists). The per-format pipeline lives here and is created lazily
//! on first use.
//!
//! Cache shape: `(depth_format, color_format, flags, extra targets)` →
//! `MTLRenderPipelineState*`, where `flags` carries `HAS_COLOR` /
//! `HAS_DEPTH` / `HAS_STENCIL` and the extra targets are render targets
//! 1..3 of a multi-target pass. Shadow-cascade tile
//! casters land at one combo (`Depth32Float`, no color); games with a
//! richer mid-pass `Clear` pattern grow the cache by a handful of
//! entries. Pipelines + library are process-lifetime (leaked via
//! `Retained::into_raw`) — same posture as `present`.

use std::sync::{Mutex, OnceLock};

use mtld3d_shared::{
    MetalHandle,
    mtl::{ClearQuadFlags, PixelFormat},
    mtl_handle::{MTLFunctionKind, MTLRenderPipelineStateKind},
};
use objc2::{rc::Retained, runtime::ProtocolObject};
use objc2_foundation::NSString;
use objc2_metal::{
    MTLCompileOptions, MTLDevice, MTLLanguageVersion, MTLLibrary, MTLMathMode, MTLPixelFormat,
    MTLRenderPipelineDescriptor,
};
use rustc_hash::FxHashMap;

use super::texture::mtl_pixel_format;
use crate::{
    LOG_TARGET,
    metal::handle::{IntoRetained, keep_first},
};

/// MSL source for the clear-quad library.
///
/// Vertex stage `mtld3d_clear_quad_vs` synthesises a fullscreen triangle
/// from `vertex_id` (0..3) and writes the caller-supplied clear value
/// from `setVertexBytes` at buffer slot 0 as the position's `z`. The
/// triangle's vertices span `[-1, 3]^2` in clip-space so its visible
/// region covers exactly `[-1, 1]^2` — the scissor (set by the PE side
/// to the D3D9 viewport rect) constrains writes to the requested
/// sub-rect of the attachment.
///
/// Fragment stage `mtld3d_clear_quad_ps_color` writes a caller-supplied
/// clear color from `setFragmentBytes` at buffer slot 0 to the bound
/// color attachment. The depth-write side of the clear is gated by the
/// PE-side depth-stencil state (`depth_test = always, depth_write =
/// on`) which writes the VS's `z` to the depth attachment uniformly
/// across the scissored fragments.
///
/// `mtld3d_clear_quad_ps_void` is the depth-only variant: a fragment
/// function that writes nothing, so the depth-stencil planes take the
/// vertex stage's `z` and the stencil reference while the colour attachment,
/// where the pass has one, sits behind an empty write mask. Metal also
/// accepts a pipeline with no fragment function for that job, and one GPU
/// family, given such a pipeline and a stencil attachment format, rasterises
/// past the scissor rectangle; the empty function keeps every family to the
/// rect. Shadow-cascade tile casters use this variant; the with-color
/// variant exists for games that mid-pass Clear color too. Multi-target
/// passes get a colour variant per present-slot mask, generated by
/// `color_ps_source` and compiled on first use.
const CLEAR_QUAD_MSL: &str = r"
#include <metal_stdlib>
using namespace metal;

struct ClearVsOut {
    float4 position [[position]];
};

vertex ClearVsOut mtld3d_clear_quad_vs(
    uint vid [[vertex_id]],
    constant float &z [[buffer(0)]]
) {
    // Fullscreen triangle: vid=0 (-1,-1), vid=1 (3,-1), vid=2 (-1,3).
    float2 p = float2(float((vid << 1u) & 2u) * 2.0 - 1.0,
                      float(vid & 2u) * 2.0 - 1.0);
    ClearVsOut out;
    out.position = float4(p, z, 1.0);
    return out;
}

fragment float4 mtld3d_clear_quad_ps_color(
    constant float4 &rgba [[buffer(0)]]
) {
    return rgba;
}

fragment void mtld3d_clear_quad_ps_void() {}
";

/// VS entry-point name.
///
/// Must match the `vertex` function declaration in `CLEAR_QUAD_MSL`.
const VS_NAME: &str = "mtld3d_clear_quad_vs";
/// PS entry-point name for the color-writing variant.
const PS_COLOR_NAME: &str = "mtld3d_clear_quad_ps_color";
/// PS entry-point name for the depth-stencil-only variant, which writes nothing.
const PS_VOID_NAME: &str = "mtld3d_clear_quad_ps_void";

#[derive(Hash, PartialEq, Eq, Clone, Copy)]
struct ClearQuadKey {
    depth_format: PixelFormat,
    color_format: PixelFormat,
    flags: ClearQuadFlags,
    /// Bit `i` = render target `i + 1` declared; its format in `extra_formats[i]`.
    extra_present_mask: u8,
    extra_formats: [PixelFormat; 3],
    /// `rasterSampleCount` of the pass the quad is drawn in.
    sample_count: u32,
}

struct ClearQuadCache {
    vs_fn: MetalHandle<MTLFunctionKind>,
    ps_color_fn: MetalHandle<MTLFunctionKind>,
    ps_void_fn: MetalHandle<MTLFunctionKind>,
    /// Colour fragment functions for multi-target passes, keyed by present mask (1..=7).
    ///
    /// Each writes the clear colour to slot 0 and to every slot in the mask;
    /// compiled from `color_ps_source` on first use.
    ps_color_fns_by_mask: Mutex<FxHashMap<u8, MetalHandle<MTLFunctionKind>>>,
    pipelines: Mutex<FxHashMap<ClearQuadKey, MetalHandle<MTLRenderPipelineStateKind>>>,
}

static CACHE: OnceLock<Option<ClearQuadCache>> = OnceLock::new();

/// Lazy create-or-fetch of the clear-quad pipeline for the requested format combo.
///
/// Returns `None` on any compile / pipeline-create failure; the PE side
/// then falls back to the legacy `end_current_pass` path (sub-rect Clear
/// semantics regress, but the game still renders).
pub fn ensure_clear_quad_pipeline(
    device: &ProtocolObject<dyn MTLDevice>,
    depth_format: PixelFormat,
    color_format: PixelFormat,
    flags: ClearQuadFlags,
    extra: &mtld3d_core::pipeline_state::ExtraColorAttachments,
    sample_count: u32,
) -> Option<MetalHandle<MTLRenderPipelineStateKind>> {
    let cache = CACHE
        .get_or_init(|| build_library_and_functions(device))
        .as_ref()?;

    let extra_present_mask = extra.present_mask & 0x7;
    let key = ClearQuadKey {
        depth_format,
        color_format,
        flags,
        extra_present_mask,
        // Normalise absent slots so single-target keys never fragment.
        extra_formats: core::array::from_fn(|i| {
            if extra_present_mask & (1 << i) != 0 {
                extra.formats[i]
            } else {
                PixelFormat::Bgra8Unorm
            }
        }),
        sample_count: sample_count.max(1),
    };

    {
        let pipelines = cache.pipelines.lock().ok()?;
        if let Some(&handle) = pipelines.get(&key) {
            return Some(handle);
        }
    }

    let handle = build_pipeline(device, cache, &key)?;
    let mut pipelines = cache.pipelines.lock().ok()?;
    // SAFETY: `build_pipeline` handed `handle` the only retain on its
    // pipeline, and nothing else copied it.
    Some(unsafe { keep_first(&mut pipelines, key, handle) })
}

fn build_library_and_functions(device: &ProtocolObject<dyn MTLDevice>) -> Option<ClearQuadCache> {
    let source = NSString::from_str(CLEAR_QUAD_MSL);
    let options = MTLCompileOptions::new();
    options.setLanguageVersion(MTLLanguageVersion::Version2_4);
    // Pin `mathMode = Fast` (default for MSL ≤ 3.1, `Relaxed` for ≥ 3.2 —
    // future-proof against an MSL bump). The clear-quad shader does a
    // constant-fed `out.color = u.color` write; the math-mode pin matters
    // only as documentation parity with the other compile sites here.
    options.setMathMode(MTLMathMode::Fast);
    let library = match device.newLibraryWithSource_options_error(&source, Some(&options)) {
        Ok(lib) => lib,
        Err(e) => {
            log::error!(
                target: LOG_TARGET,
                "clear-quad: MSL compilation failed: {e}"
            );
            return None;
        }
    };
    library.setLabel(Some(&NSString::from_str("mtld3d-clear-quad")));

    let vs = library.newFunctionWithName(&NSString::from_str(VS_NAME))?;
    let ps_color = library.newFunctionWithName(&NSString::from_str(PS_COLOR_NAME))?;
    let ps_void = library.newFunctionWithName(&NSString::from_str(PS_VOID_NAME))?;

    // Library is kept alive by the function refs; the function refs
    // are kept alive by the pipeline states once they're built.
    // Intentionally leak the function handles for process lifetime
    // so build_pipeline can re-derive `&ProtocolObject<dyn
    // MTLFunction>` from them per pipeline-build.
    // SAFETY: Retained::into_raw transfers the retain into the typed handle.
    let vs_handle = unsafe { MetalHandle::<MTLFunctionKind>::new(Retained::into_raw(vs) as u64) };
    // SAFETY: Retained::into_raw transfers the retain into the typed handle.
    let ps_color_handle =
        unsafe { MetalHandle::<MTLFunctionKind>::new(Retained::into_raw(ps_color) as u64) };
    // SAFETY: as above.
    let ps_void_handle =
        unsafe { MetalHandle::<MTLFunctionKind>::new(Retained::into_raw(ps_void) as u64) };
    drop(library);

    Some(ClearQuadCache {
        vs_fn: vs_handle,
        ps_color_fn: ps_color_handle,
        ps_void_fn: ps_void_handle,
        ps_color_fns_by_mask: Mutex::new(FxHashMap::default()),
        pipelines: Mutex::new(FxHashMap::default()),
    })
}

/// Entry-point name of the colour fragment function for `extra_present_mask`.
fn color_ps_name(extra_present_mask: u8) -> String {
    format!("{PS_COLOR_NAME}_m{extra_present_mask}")
}

/// MSL for a colour fragment function writing the clear colour to slot 0 and the masked slots.
///
/// Metal rejects a fragment function that writes a colour slot the pass
/// leaves unbound, so each distinct present mask gets its own function.
fn color_ps_source(extra_present_mask: u8) -> String {
    use std::fmt::Write;
    let mut msl = String::from("#include <metal_stdlib>\nusing namespace metal;\n\n");
    msl.push_str("struct ClearPsOut {\n    float4 c0 [[color(0)]];\n");
    for i in 0..3u32 {
        if extra_present_mask & (1 << i) != 0 {
            let _ = writeln!(msl, "    float4 c{slot} [[color({slot})]];", slot = i + 1);
        }
    }
    msl.push_str("};\n\n");
    let _ = writeln!(
        msl,
        "fragment ClearPsOut {}(\n    constant float4 &rgba [[buffer(0)]]\n) {{\n    ClearPsOut out;\n    out.c0 = rgba;",
        color_ps_name(extra_present_mask)
    );
    for i in 0..3u32 {
        if extra_present_mask & (1 << i) != 0 {
            let _ = writeln!(msl, "    out.c{} = rgba;", i + 1);
        }
    }
    msl.push_str("    return out;\n}\n");
    msl
}

/// Colour fragment function for `key`: the shared one on a single-target pass, else per mask.
fn color_ps_function(
    device: &ProtocolObject<dyn MTLDevice>,
    cache: &ClearQuadCache,
    extra_present_mask: u8,
) -> Option<Retained<ProtocolObject<dyn objc2_metal::MTLFunction>>> {
    if extra_present_mask == 0 {
        return cache.ps_color_fn.into_retained();
    }
    {
        let fns = cache.ps_color_fns_by_mask.lock().ok()?;
        if let Some(handle) = fns.get(&extra_present_mask) {
            return handle.into_retained();
        }
    }
    let source = NSString::from_str(&color_ps_source(extra_present_mask));
    let options = MTLCompileOptions::new();
    options.setLanguageVersion(MTLLanguageVersion::Version2_4);
    options.setMathMode(MTLMathMode::Fast);
    let library = match device.newLibraryWithSource_options_error(&source, Some(&options)) {
        Ok(lib) => lib,
        Err(e) => {
            log::error!(
                target: LOG_TARGET,
                "clear-quad: multi-target MSL (mask {extra_present_mask:#x}) failed to compile: {e}"
            );
            return None;
        }
    };
    library.setLabel(Some(&NSString::from_str(&format!(
        "mtld3d-clear-quad-mrt-{extra_present_mask:#x}"
    ))));
    let function =
        library.newFunctionWithName(&NSString::from_str(&color_ps_name(extra_present_mask)))?;
    // Process-lifetime, like the single-target functions.
    // SAFETY: Retained::into_raw transfers the retain into the typed handle.
    let handle =
        unsafe { MetalHandle::<MTLFunctionKind>::new(Retained::into_raw(function) as u64) };
    let mut fns = cache.ps_color_fns_by_mask.lock().ok()?;
    // SAFETY: `into_raw` above handed `handle` the only retain on the
    // function, and nothing else copied it.
    unsafe { keep_first(&mut fns, extra_present_mask, handle) }.into_retained()
}

/// Declare render targets 1..3 on the pipeline, writing colour or not as `write` says.
fn declare_extra_color_attachments(
    desc: &MTLRenderPipelineDescriptor,
    key: &ClearQuadKey,
    write: bool,
) {
    for i in 0..3usize {
        if key.extra_present_mask & (1 << i) == 0 {
            continue;
        }
        // SAFETY: `colorAttachments()` returns a non-null descriptor array;
        // subscripts 1..=3 are within Metal's colour attachment count.
        let color = unsafe { desc.colorAttachments().objectAtIndexedSubscript(i + 1) };
        color.setPixelFormat(mtl_pixel_format(key.extra_formats[i]));
        if !write {
            color.setWriteMask(objc2_metal::MTLColorWriteMask::empty());
        }
    }
}

fn build_pipeline(
    device: &ProtocolObject<dyn MTLDevice>,
    cache: &ClearQuadCache,
    key: &ClearQuadKey,
) -> Option<MetalHandle<MTLRenderPipelineStateKind>> {
    let vs = cache.vs_fn.into_retained()?;
    let has_color = key.flags.contains(ClearQuadFlags::HAS_COLOR);
    let has_depth = key.flags.contains(ClearQuadFlags::HAS_DEPTH);
    let has_stencil = key.flags.contains(ClearQuadFlags::HAS_STENCIL);

    let desc = MTLRenderPipelineDescriptor::new();
    desc.setVertexFunction(Some(&vs));
    desc.setRasterSampleCount(key.sample_count as usize);

    if has_color {
        let ps_color = color_ps_function(device, cache, key.extra_present_mask)?;
        desc.setFragmentFunction(Some(&ps_color));
        // SAFETY: `colorAttachments()` returns a non-null `MTLRenderPipeline-
        // ColorAttachmentDescriptorArray`; subscript 0 is always valid.
        let color0 = unsafe { desc.colorAttachments().objectAtIndexedSubscript(0) };
        color0.setPixelFormat(mtl_pixel_format(key.color_format));
        declare_extra_color_attachments(&desc, key, true);
        drop(ps_color);
    } else {
        // Depth-stencil-only pipeline: the fragment function that writes
        // nothing (see `CLEAR_QUAD_MSL` for why it is a function rather than
        // `fragmentFunction = nil`), and the VS's z-write alone drives the
        // depth attachment under the `depth_write = on` depth-stencil state.
        let ps_void = cache.ps_void_fn.into_retained()?;
        desc.setFragmentFunction(Some(&ps_void));
        if key.flags.contains(ClearQuadFlags::COLOR_FORMAT_NO_WRITE) {
            // The pass still has a colour attachment bound, so the pipeline
            // must declare its format (Metal validates pipeline-vs-pass colour
            // format even for a draw that writes no colour) — but with a zero
            // write mask, since this is a depth-only clear.
            // SAFETY: `colorAttachments()` returns a non-null descriptor array;
            // subscript 0 is always valid.
            let color0 = unsafe { desc.colorAttachments().objectAtIndexedSubscript(0) };
            color0.setPixelFormat(mtl_pixel_format(key.color_format));
            color0.setWriteMask(objc2_metal::MTLColorWriteMask::empty());
            declare_extra_color_attachments(&desc, key, false);
        }
    }

    // Depth attachment formats — mirror `pipeline::create_render_pipeline`'s
    // rule: only set the stencil pixel format when the depth format actually
    // carries stencil bits; mismatched stencil format makes Metal reject the
    // pipeline at draw time. When the pass has NO depth attachment (`HAS_DEPTH`
    // unset — e.g. a color clear-quad after `SetDepthStencilSurface(NULL)`),
    // leave Metal's default `.invalid`: declaring a depth format against a
    // depth-less render pass is rejected ("depth attachment pixelFormat must be
    // Invalid, as no texture is set").
    if has_stencil {
        desc.setDepthAttachmentPixelFormat(MTLPixelFormat::Depth32Float_Stencil8);
        desc.setStencilAttachmentPixelFormat(MTLPixelFormat::Depth32Float_Stencil8);
    } else if has_depth {
        desc.setDepthAttachmentPixelFormat(mtl_pixel_format(key.depth_format));
    }

    let label = format!(
        "mtld3d-clear-quad d={} c={:?}{}{}{}",
        if has_depth {
            format!("{:?}", key.depth_format)
        } else {
            "none".to_owned()
        },
        if has_color {
            key.color_format
        } else {
            PixelFormat::Bgra8Unorm
        },
        if has_color { "" } else { " no-color" },
        if has_stencil { " +stencil" } else { "" },
        if key.extra_present_mask == 0 {
            String::new()
        } else {
            format!(" mrt={:#x}", key.extra_present_mask)
        },
    );
    desc.setLabel(Some(&NSString::from_str(&label)));

    let pipeline = match device.newRenderPipelineStateWithDescriptor_error(&desc) {
        Ok(p) => p,
        Err(e) => {
            log::error!(
                target: LOG_TARGET,
                "clear-quad: pipeline creation failed ({label}): {e}"
            );
            return None;
        }
    };
    drop(vs);
    // SAFETY: Retained::into_raw transfers the retain into the typed handle.
    Some(unsafe {
        MetalHandle::<MTLRenderPipelineStateKind>::new(Retained::into_raw(pipeline) as u64)
    })
}

#[cfg(test)]
mod tests;
