[package]
name = "mtld3d-d3d8"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Direct3D 8 frontend for mtld3d"
authors.workspace = true

[lib]
name = "d3d8"
crate-type = ["cdylib"]

[dependencies]
mtld3d-core.workspace = true
mtld3d-d3d8-types.workspace = true
mtld3d-types.workspace = true
mtld3d-shared.workspace = true
log.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
